export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GETALLUSER_REQUEST = "GETALLUSER_REQUEST"
export const GETALLUSER_SUCCESS = "GETALLUSER_SUCCESS"
export const GETALLUSER_FAIL = "GETALLUSER_FAIL"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const GET_CURR_USER_REQUEST = "GET_CURR_USER_REQUEST"
export const GET_CURR_USER_SUCCESS = "GET_CURR_USER_SUCCESS"
export const GET_CURR_USER_FAIL = "GET_CURR_USER_FAIL"

export const UPLOAD_POST_REQUEST = "UPLOAD_POST_REQUEST"
export const UPLOAD_POST_SUCESS = "UPLOAD_POST_SUCESS"
export const UPLOAD_POST_FAIL = "UPLOAD_POST_FAIL"

export const GETALLPOST_REQUEST = "GETALLPOST_REQUEST"
export const GETALLPOST_SUCCESS = "GETALLPOST_SUCCESS"
export const GETALLPOST_FAIL = "GETALLPOST_FAIL"

export const SET_TOTAL_LENGTH = "SET_TOTAL_LENGTH"
export const SET_HAS_MORE = "SET_HAS_MORE"
